version: "3.9"
services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./data:/data
    environment:
      DATABASE_URL: sqlite:////data/year_in_data.db
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.8'
          memory: 400M
