"""Refactor strong workout columns

Revision ID: 24a93bb80730
Revises: e2e68fe3f052
Create Date: 2025-04-24 14:16:10.347656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24a93bb80730'
down_revision: Union[str, None] = 'e2e68fe3f052'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM strong_workouts")
    op.drop_column('strong_workouts', 'total_sets')
    op.drop_column('strong_workouts', 'distance')
    op.drop_column('strong_workouts', 'exercise_name')
    op.drop_column('strong_workouts', 'total_reps')
    op.drop_column('strong_workouts', 'max_weight')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM strong_workouts")
    op.add_column('strong_workouts', sa.Column('max_weight', sa.FLOAT(), nullable=True))
    op.add_column('strong_workouts', sa.Column('total_reps', sa.INTEGER(), nullable=False))
    op.add_column('strong_workouts', sa.Column('exercise_name', sa.VARCHAR(), nullable=False))
    op.add_column('strong_workouts', sa.Column('distance', sa.INTEGER(), nullable=False))
    op.add_column('strong_workouts', sa.Column('total_sets', sa.INTEGER(), nullable=False))
    # ### end Alembic commands ###
