"""Add page flip columns to kindle_reading

Revision ID: 3f12b644a560
Revises: 24a93bb80730
Create Date: 2025-04-24 15:39:29.287476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f12b644a560'
down_revision: Union[str, None] = '24a93bb80730'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kindle_reading', sa.Column('number_of_page_flips', sa.Integer(), nullable=False, comment='value_column [pages]', default=0))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kindle_reading', 'number_of_page_flips')
    # ### end Alembic commands ###
