"""Rename fibit_steps to fitbit_steps

Revision ID: 4eb5ab509a18
Revises: fe9e3f5f9c1c
Create Date: 2025-04-11 13:17:08.556683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4eb5ab509a18'
down_revision: Union[str, None] = 'fe9e3f5f9c1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("fibit_steps", "fitbit_steps")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("fitit_steps", "fibit_steps")
    # ### end Alembic commands ###
