"""Create kindle_reading table.

Revision ID: 8e8b1598f1a9
Revises: e14dffd41751
Create Date: 2025-04-06 10:29:12.743718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e8b1598f1a9'
down_revision: Union[str, None] = 'e14dffd41751'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kindle_reading',
    sa.Column('id', sa.Integer(), nullable=False, comment='primary_key'),
    sa.Column('date', sa.Date(), nullable=False, comment='date_column'),
    sa.Column('start_time', sa.Time(), nullable=False, comment='time_column'),
    sa.Column('asin', sa.String(), nullable=False, comment='category_column'),
    sa.Column('total_reading_minutes', sa.Integer(), nullable=False, comment='value_column'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kindle_reading_id'), 'kindle_reading', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_kindle_reading_id'), table_name='kindle_reading')
    op.drop_table('kindle_reading')
    # ### end Alembic commands ###
