"""Create strong workouts

Revision ID: e14dffd41751
Revises: 
Create Date: 2025-04-05 21:14:46.936126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e14dffd41751'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('strong_workouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('workout_name', sa.String(), nullable=False),
    sa.Column('exercise_name', sa.String(), nullable=False),
    sa.Column('total_sets', sa.Integer(), nullable=False),
    sa.Column('max_weight', sa.Float(), nullable=True),
    sa.Column('total_reps', sa.Integer(), nullable=False),
    sa.Column('total_volume', sa.Float(), nullable=False),
    sa.Column('workout_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('distance', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strong_workouts_id'), 'strong_workouts', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_strong_workouts_id'), table_name='strong_workouts')
    op.drop_table('strong_workouts')
    # ### end Alembic commands ###
