"""Create strong workout tables

Revision ID: f37116511d67
Revises: 
Create Date: 2025-04-05 20:39:05.665290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f37116511d67'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_strong_workouts_id', table_name='strong_workouts')
    op.drop_table('strong_workouts')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('strong_workouts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('workout_name', sa.VARCHAR(), nullable=False),
    sa.Column('exercise_name', sa.VARCHAR(), nullable=False),
    sa.Column('total_sets', sa.INTEGER(), nullable=False),
    sa.Column('max_weight', sa.FLOAT(), nullable=True),
    sa.Column('total_reps', sa.INTEGER(), nullable=False),
    sa.Column('total_volume', sa.FLOAT(), nullable=False),
    sa.Column('workout_duration_minutes', sa.INTEGER(), nullable=False),
    sa.Column('distance', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_strong_workouts_id', 'strong_workouts', ['id'], unique=False)
    # ### end Alembic commands ###
