"""Create fibit tables.

Revision ID: fe9e3f5f9c1c
Revises: 8e8b1598f1a9
Create Date: 2025-04-06 12:07:25.870269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe9e3f5f9c1c'
down_revision: Union[str, None] = '8e8b1598f1a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fibit_steps',
    sa.Column('id', sa.Integer(), nullable=False, comment='primary_key'),
    sa.Column('date', sa.Date(), nullable=False, comment='date_column'),
    sa.Column('value', sa.Float(), nullable=False, comment='value_column'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fibit_steps_id'), 'fibit_steps', ['id'], unique=False)
    op.create_table('fitbit_calories',
    sa.Column('id', sa.Integer(), nullable=False, comment='primary_key'),
    sa.Column('date', sa.Date(), nullable=False, comment='date_column'),
    sa.Column('value', sa.Float(), nullable=False, comment='value_column'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fitbit_calories_id'), 'fitbit_calories', ['id'], unique=False)
    op.create_table('fitbit_exercises',
    sa.Column('id', sa.Integer(), nullable=False, comment='primary_key'),
    sa.Column('date', sa.Date(), nullable=False, comment='date_column'),
    sa.Column('activity_name', sa.String(), nullable=False, comment='category_column'),
    sa.Column('average_heart_rate', sa.Integer(), nullable=True, comment='value_column'),
    sa.Column('calories', sa.Integer(), nullable=False, comment='value_column'),
    sa.Column('distance', sa.Integer(), nullable=True, comment='value_column'),
    sa.Column('active_duration', sa.Integer(), nullable=False, comment='value_column'),
    sa.Column('start_time', sa.Time(), nullable=False, comment='time_column'),
    sa.Column('pace', sa.Float(), nullable=True, comment='value_column'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fitbit_exercises_id'), 'fitbit_exercises', ['id'], unique=False)
    op.create_table('fitbit_sleep',
    sa.Column('id', sa.Integer(), nullable=False, comment='primary_key'),
    sa.Column('date', sa.Date(), nullable=False, comment='date_column'),
    sa.Column('start_time', sa.Time(), nullable=False, comment='time_column'),
    sa.Column('end_time', sa.Time(), nullable=False, comment='time_column'),
    sa.Column('total_duration_hours', sa.Float(), nullable=False, comment='value_column'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fitbit_sleep_id'), 'fitbit_sleep', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fitbit_sleep_id'), table_name='fitbit_sleep')
    op.drop_table('fitbit_sleep')
    op.drop_index(op.f('ix_fitbit_exercises_id'), table_name='fitbit_exercises')
    op.drop_table('fitbit_exercises')
    op.drop_index(op.f('ix_fitbit_calories_id'), table_name='fitbit_calories')
    op.drop_table('fitbit_calories')
    op.drop_index(op.f('ix_fibit_steps_id'), table_name='fibit_steps')
    op.drop_table('fibit_steps')
    # ### end Alembic commands ###
